from enum import Enum


class Format(str, Enum):
    PROPERTIES = "properties"
    XML = "xml"
    YAML = "yaml"


class RunStatus(str, Enum):
    INITIALIZED = "INITIALIZED"
    BACKED_UP = "BACKED_UP"
    UPGRADE_EXECUTED = "UPGRADE_EXECUTED"
    AFTER_CAPTURED = "AFTER_CAPTURED"
    COMPARED = "COMPARED"
    RATIONALIZED = "RATIONALIZED"
    VALIDATED = "VALIDATED"
    REVIEWED = "REVIEWED"
    APPLIED = "APPLIED"
    ROLLED_BACK = "ROLLED_BACK"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_ERRORS = "COMPLETED_WITH_ERRORS"
    FAILED = "FAILED"


class Severity(str, Enum):
    INFORMATIONAL = "INFORMATIONAL"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ChangeType(str, Enum):
    UNCHANGED = "UNCHANGED"
    TRIVIAL_CHANGES_ONLY = "TRIVIAL_CHANGES_ONLY"
    ADDED_FILE = "ADDED_FILE"
    REMOVED_FILE = "REMOVED_FILE"
    ADDED = "ADDED"
    REMOVED_BY_VENDOR = "REMOVED_BY_VENDOR"
    VENDOR_VALUE_CHANGED = "VENDOR_VALUE_CHANGED"
    TYPE_CHANGED = "TYPE_CHANGED"
    LIST_CHANGED = "LIST_CHANGED"
    STRUCTURE_CHANGED = "STRUCTURE_CHANGED"
    XML_SCHEMA_CHANGED = "XML_SCHEMA_CHANGED"
    XML_SCHEMA_UNKNOWN = "XML_SCHEMA_UNKNOWN"
    AMBIGUOUS_NODE_IDENTITY = "AMBIGUOUS_NODE_IDENTITY"
    PARSE_ERROR = "PARSE_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    EXCLUDED_FROM_RATIONALIZATION = "EXCLUDED_FROM_RATIONALIZATION"


class Action(str, Enum):
    ADD_VENDOR_DEFAULT = "ADD_VENDOR_DEFAULT"
    KEEP_BACKUP = "KEEP_BACKUP"
    EXCLUDE_FILE = "EXCLUDE_FILE"
    REVIEW = "REVIEW"
    NONE = "NONE"


class Ownership(str, Enum):
    TARGET = "TARGET"
    UNRELATED = "UNRELATED"
    SHARED = "SHARED"
    UNKNOWN = "UNKNOWN"


class ModuleStatus(str, Enum):
    ENABLED = "ENABLED"
    SKIPPED_BY_USER = "SKIPPED_BY_USER"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"